<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../Tests.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\CommandQuery.Tests\Fake.cs" Link="Fake.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.1.21" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CommandQuery.GoogleCloudFunctions\CommandQuery.GoogleCloudFunctions.csproj" />
  </ItemGroup>

</Project>
