<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../Tests.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CommandQuery.Client\CommandQuery.Client.csproj" />
    <ProjectReference Include="..\..\src\CommandQuery.SystemTextJson\CommandQuery.SystemTextJson.csproj" />
    <ProjectReference Include="..\..\src\CommandQuery\CommandQuery.csproj" />
    <ProjectReference Include="..\CommandQuery.Fail\CommandQuery.Fail.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\samples\CommandQuery.Sample.Contracts\Commands\*.cs" LinkBase="Client\Contracts\Commands" />
    <Compile Include="..\..\samples\CommandQuery.Sample.Contracts\Queries\*.cs" LinkBase="Client\Contracts\Queries" />
  </ItemGroup>

</Project>
